wandb_version: 1

Dataset:
  desc: null
  value: Glaucoma
Models:
  desc: null
  value: Xception
learning_rate:
  desc: null
  value: 0.001
beta1:
  desc: null
  value: 0.9
metrics:
  desc: null
  value:
  - accuracy
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683111879.651109
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 5
      - 13
      - 14
      - 16
      - 23
      4: 3.9.12
      5: 0.15.1
      8:
      - 1
      - 3
      - 5
